[package]
name = "rust-tests"
version = "0.1.0"
description = "Ledger-app integration tests using Solana tools"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]

[dev-dependencies]
hex = "0.4.1"
serial_test = "0.3.2"
serial_test_derive = "0.3.1"
solana-remote-wallet = { git = "https://github.com/solana-labs/solana", rev = "0bbee94" }
solana-sdk = { git = "https://github.com/solana-labs/solana", rev = "0bbee94" }
